version: "1.0"
servers:
  - id: server_1755530323761_1700hkfml
    name: cds
    endpointUrl: opc.tcp://DESKTOP-U99TJH0:51310/CogentDataHub/DataAccess
    securityPolicy: http://opcfoundation.org/UA/SecurityPolicy#None
    securityMode: None
    userAuthMethod: anonymous
    trustUnknownCerts: true
    samplingInterval: 1000
    maxSessionSubscriptions: 10
    redundantEndpoints: []
    enabled: true
loops:
  - loopId: LOOP-001
    serverId: demo-server
    tags:
      pv:
        nodeId: ns=2;s=Process.PV
        samplingInterval: 200
        queueSize: 10
        discardOldest: true
      op:
        nodeId: ns=2;s=Process.OP
        samplingInterval: 200
        queueSize: 10
        discardOldest: true
      sp:
        nodeId: ns=2;s=Process.SP
        samplingInterval: 1000
        queueSize: 5
        discardOldest: true
      mode:
        nodeId: ns=2;s=Process.Mode
        samplingInterval: 5000
        queueSize: 3
        discardOldest: true
    enabled: true
    createdAt: 2025-08-18T14:29:51.222Z
    updatedAt: 2025-08-18T14:39:06.799Z
  - loopId: LOOP-002
    serverId: demo-server
    tags:
      pv:
        nodeId: ns=2;s=Tank.Level
        samplingInterval: 500
        queueSize: 10
        discardOldest: true
        deadbandAbsolute: 0.1
      op:
        nodeId: ns=2;s=Tank.Valve
        samplingInterval: 500
        queueSize: 10
        discardOldest: true
        deadbandPercent: 1
    enabled: true
    createdAt: 2025-08-18T14:29:51.222Z
    updatedAt: 2025-08-18T14:39:06.799Z
  - loopId: LOOP-003
    serverId: production-server-1
    tags:
      pv:
        nodeId: ns=3;s=Reactor.Temperature
        samplingInterval: 200
        queueSize: 20
        discardOldest: true
        deadbandAbsolute: 0.5
      op:
        nodeId: ns=3;s=Reactor.Heater.Output
        samplingInterval: 200
        queueSize: 20
        discardOldest: true
      sp:
        nodeId: ns=3;s=Reactor.Temperature.Setpoint
        samplingInterval: 1000
        queueSize: 5
        discardOldest: true
      mode:
        nodeId: ns=3;s=Reactor.Control.Mode
        samplingInterval: 5000
        queueSize: 3
        discardOldest: true
    enabled: true
    createdAt: 2025-08-18T14:29:51.222Z
    updatedAt: 2025-08-18T14:39:06.799Z
  - loopId: LOOP-004
    serverId: production-server-1
    tags:
      pv:
        nodeId: ns=3;s=Distillation.Column.Pressure
        samplingInterval: 1000
        queueSize: 10
        discardOldest: true
      valve:
        nodeId: ns=3;s=Distillation.Column.Valve.Position
        samplingInterval: 500
        queueSize: 15
        discardOldest: true
    enabled: false
    createdAt: 2025-08-18T14:29:51.222Z
    updatedAt: 2025-08-18T14:39:06.799Z
